name: bookworm
version: '1.0.0'
summary: A focused eBook reader
description: |
  Read the books you love without having to worry about the different format complexities like epub, pdf, mobi, cbr, etc
  Manage your library by tagging and updating metadata on books, to quickly find books using metadata searching and tag based filtering.
  This version supports EPUB, MOBI, PRC, PDF and Comics (CBR and CBZ) formats with support for more formats to follow soon.

icon: data/icons/24/com.github.babluboy.bookworm.svg
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

slots:
  dbus-bookworm:
    interface: dbus
    bus: session
    name: com.github.babluboy.bookworm

apps:
  bookworm:
    command: desktop-launch com.github.babluboy.bookworm
    slots: [ dbus-bookworm ]
    desktop: usr/share/applications/com.github.babluboy.bookworm.desktop
    plugs: [network, home, x11, unity7, gsettings, browser-support]
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/:$LD_LIBRARY_PATH

parts:
    granite:
        plugin: cmake
        source: https://github.com/elementary/granite/archive/0.5.tar.gz
        source-type: tar
        configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/usr, -DCMAKE_INSTALL_LIBDIR=/usr/lib]
        build-packages:
            - build-essential
            - libgee-0.8-dev
            - libgirepository1.0-dev
            - libgtk-3-dev
            - cmake
            - gobject-introspection
                
    bookworm:
        after: [granite, desktop-gtk3]
        source: https://github.com/babluboy/bookworm/archive/1.0.0.tar.gz
        source-type: tar
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr]
        build-packages:
            - build-essential
            - valac
            - intltool
            - libgee-0.8-dev
            - debhelper
            - libgtk-3-dev
            - libgranite-dev
            - libwebkit2gtk-4.0-37
            - libwebkit2gtk-4.0-dev
            - libsqlite3-dev
            - poppler-utils
            - libpoppler-glib-dev
            - libsoup2.4-dev
            - libxml2-dev
        stage-packages:
            - gnome-keyring
            - gobject-introspection
            - libgdk-pixbuf2.0-0
            - libgee-0.8-2
            - libgtk-3-0
            - libpango-1.0-0
            - libcairo2
            - libpangocairo-1.0-0
            - libsqlite3-0
            - libwebkit2gtk-4.0-37
            - libxml2
            - dbus-x11
    valac:
      plugin: autotools
      source: http://download.gnome.org/sources/vala/0.38/vala-0.38.8.tar.xz
      build-packages:
         - flex    
         - bison
         - build-essential
         - libglib2.0-dev
         - libgraphviz-dev
