name: bookworm
version: '1.0.0'
summary: A focused eBook reader
description: |
  Read the books you love without having to worry about the different format complexities like epub, pdf, mobi, cbr, etc
  Manage your library by tagging and updating metadata on books, to quickly find books using metadata searching and tag based filtering.
  This version supports EPUB, MOBI, PRC, PDF and Comics (CBR and CBZ) formats with support for more formats to follow soon.

icon: /usr/share/icons/hicolor/24x24/apps/com.github.babluboy.bookworm.svg
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  bookworm:
    command: desktop-launch com.github.babluboy.bookworm
    desktop: usr/share/applications/com.github.babluboy.bookworm.desktop
    plugs: [home, x11, unity7, gsettings]

parts:
    bookworm:
        source: https://github.com/babluboy/bookworm.git
        plugin: cmake        
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr]
        build-packages:
            - build-essential
            - valac
            - intltool
            - libgee-0.8-dev
            - debhelper
            - libgtk-3-dev
            - libgranite-dev
            - libwebkit2gtk-4.0-37
            - libwebkit2gtk-4.0-dev
            - libsqlite3-dev
            - libpoppler-glib-dev
        stage-packages:
            - gnome-keyring
            - gobject-introspection
            - libgdk-pixbuf2.0-0
            - libgee-0.8-2
            - libgtk-3-0
            - libpango-1.0-0
            - libpangocairo-1.0-0
        after: [desktop-gtk3]
